name: 🐛 Bug

description: Report an issue to help improve the project.

title: '🐛 [ISSUE]: <description>'

body:

  - type: textarea

    id: description

    attributes:

      label: Description

      description: A brief description of the question or issue, also include what you've already tried and didn't work

    validations:

      required: true

  - type: textarea

    id: screenshots

    attributes:

      label: Screenshots

      description: Please add screenshots (if applicable)

    validations:

      required: false

  - type: textarea

    id: extrainfo

    attributes:

      label: Additional information

      description: Is there anything else you want to tell about this bug?

    validations:

      required: false

  - type: markdown

    attributes:

      value: "> Feel free to join the links.dev community [here](https://discord.gg/KskRunFWEc)"
